name: protolith
description: Protolith, a compositional base for blockchains.
version: 1.0.0
homepage: https://github.com/protolambda/protolith
author: proto <proto@protolambda.com>
license: MIT

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  pointycastle: ^1.0.0-rc4
  web3dart: ^0.4.1

dev_dependencies:
  test: ^1.5.1
